# Imagem base do Node.js para API Backend
FROM node:18-alpine

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de dependências
COPY package*.json ./

# Instala as dependências
RUN npm install --force

# Copia o restante dos arquivos da API
COPY . .

# Expõe a porta da API (3000)
EXPOSE 3000

# Comando para iniciar a API em modo dev
CMD ["npm", "start"]
